import { z } from "zod";

export const updateLeaseSchema = z.object({
  endDate: z.string().optional(),
  rentAmount: z.number().optional(),
  leaseStatus: z.string().optional(),
  notes: z.string().optional(),
  terminationDate: z.union([z.string(), z.date()]).optional(),
  terminationReason: z.string().optional(),
  terminationNotes: z.string().optional(),
  terminatedBy: z.string().optional(),
});
export const createLeaseSchema = z.object({
  listingId: z.string().min(1),
  tenantId: z.string().nullable().optional(),
  startDate: z.union([z.string().min(1), z.date()]),
  endDate: z.union([z.string().min(1), z.date()]),
  rentAmount: z.number().positive(),
  paymentFrequency: z.enum(["DAILY", "WEEKLY", "MONTHLY", "QUARTERLY", "YEARLY"]),
  paymentMethod: z.string().optional(),
  leaseStatus: z.enum(["DRAFT", "ACTIVE", "EXPIRED", "TERMINATED"]).optional(),
  notes: z.string().optional(),
  
  // Standard lease form fields
  landlordFullName: z.string().optional(),
  additionalLandlords: z.array(z.any()).optional(),
  tenantFullName: z.string().optional(),
  tenantEmail: z.string().optional(),
  tenantPhone: z.string().optional(),
  additionalTenants: z.array(z.any()).optional(),
  propertyAddress: z.string().optional(),
  propertyCity: z.string().optional(),
  propertyState: z.string().optional(),
  propertyZipCode: z.string().optional(),
  leaseTermType: z.string().optional(),
  periodicBasis: z.string().optional(),
  periodicOther: z.string().optional(),
  fixedEndCondition: z.string().optional(),
  vacateReason: z.string().optional(),
  paymentDay: z.number().optional(),
  petDeposit: z.number().nullable().optional(),
  petDepositDueDate: z.union([z.string().min(1), z.date()]).nullable().optional(),
  securityDeposit: z.number().nullable().optional(),
  securityDepositDueDate: z.union([z.string().min(1), z.date()]).nullable().optional(),
  includedServices: z.array(z.string()).optional(),
  parkingSpaces: z.number().nullable().optional(),
});